[package]
name = "xbfisher"
version = "0.1.0"
edition = "2021"

[dependencies]
socket2 = { version = "0.5.7", features = ["all"] }
thiserror = "1.0"
rand = "0.8"
systemstat = "0.2.3"
csv = "1.3.0"
serde = {version = "1.0.204", features = ["derive"] }
chrono = "0.4.38"
regex = "1.11.1"
